---
- name: Windows 10 Disable Windows Defender
  hosts: windows10
  gather_facts: no
  tasks:
  - name: Disable Anti-Spyware
    win_shell: |
              Set-ItemProperty "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender" -Name "DisableAntiSpyware" -Type DWORD -Value 1 -Force

  - name: Make Real-Time Protection Key
    win_shell: |
              New-Item "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender" -Name "Real-Time Protection" -Type KEY -Force

  - name: Disable Realtime Monitoring via Key
    win_shell: |
              Set-ItemProperty "HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender\Real-Time Protection" -Name "DisableRealtimeMonitoring" -Type DWORD -Value 1 -Force

  - name: Disable Sample Submissions
    win_shell: |
              Set-MpPreference -SubmitSamplesConsent 0

  - name: Add C Drive Exclusion
    win_shell: |
              Add-MpPreference -ExclusionPath "C:"

  - name: Disable Realtime Monitoring via MpPreference
    win_shell: |
              Set-MpPreference -DisableRealtimeMonitoring $true
