---
- name: Windows 10 Remote Desktop Setup
  hosts: windows10
  gather_facts: no
  tasks:
  - name: Ensuring RDP is Enabled
    win_shell: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0

  - name: Adding Domain Users to RDP
    win_shell: Add-LocalGroupMember -Group "Remote Desktop Users" -Member "DOMAIN\Domain Users"