---
- name: Windows 10 Remote Desktop Setup
  hosts: windows10
  gather_facts: no
  tasks:
  - name: Ensuring RDP is Enabled
    ansible.windows.win_powershell: 
      script: | 
      Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
  - name: Adding Domain Users to RDP
    ansible.windows.win_powershell: 
      script: |
      Add-LocalGroupMember -Group "Remote Desktop Users" -Member "DOMAIN\Domain Users"